#import "../shared/macros.typ": *

= Component Deep Dive: Edge Overlay and Control Path

#component_owner("Valentin Bumeder, Jan Duchscherer")

The overlay stage merges RGB video and binary edge stream in lockstep, while the button/control path handles interactive state transitions through debouncing and click detection.

The shown overlay image evidence is parsed from stored simulation artifacts; the related target is currently treated as artifact-only in reporting because it is not registered in the active #repo_link("testbench/targets.toml") list.

== Edge Overlay Composition

#repo_link("rtl/EDGE_OVERLAY/hdl/axi_edge_overlay.vhd", body: raw("AxiEdgeOverlay"), line: 5) receives two synchronized AXI streams:

- RGB base stream (`s_axis_video_rbg888_*`)
- Edge stream (`s_axis_video_edges_*`)

If `i_overlay_enable = 1` and edge beat is non-zero, the pixel is replaced with `G_EDGE_COLOR`; otherwise the RGB beat is forwarded unchanged.

#figure(
  image("../figures/artifacts/lenna_512_512_edge_overlay_out_rgb.png", width: 82%),
  caption: [Edge overlay output artifact generated by cocotb testbench.],
) <fig-edge-overlay-output>

== Dual-Stream Handshake Policy

#mono_block([
m_axis_valid = rgb_valid && edge_valid
rgb_ready    = m_axis_ready && edge_valid
edge_ready   = m_axis_ready && rgb_valid
])

This lockstep handshake prevents one stream from advancing without the other and protects `SOF/EOL` alignment at merge points.@amd_ug934

== Control Path Modules

#academic_table(
  columns: (1.8fr, 2.2fr),
  align: (left, left),
  table.header([Module], [Role in control path]),
  [#repo_link("rtl/DEBOUNCER/hdl/debouncing.vhd", line: 5)], [stabilizes asynchronous button transitions and removes chatter],
  [#repo_link("rtl/CLICK_DETECTOR/hdl/click_detection.vhd", line: 5)], [classifies click events with state-machine based timing rules],
  [#repo_link("rtl/CLICK_DETECTOR/hdl/debounced_click_detector.vhd", line: 4)], [integration wrapper combining debouncer and click FSM],
  [#repo_link("rtl/BUTTON_EXAMPLE/hdl/button_example.vhd", line: 4)], [hardware-visible status path used in Vivado integration],
)

These modules are not in the image-processing datapath itself, but they affect usability and real-system operability when switching or enabling stream behaviors. The debouncing assumptions follow standard mechanical switch-bounce behavior summarized in #cite(<ganssle_debouncing>).
