"""Convert a binary mask image to a VHDL ROM package for synthesis-time BRAM init.

Usage
-----
    python tools/mask_to_vhdl_rom.py <input_image> [<threshold>]

    input_image : path to any image readable by Pillow (PNG, BMP, JPEG, …)
    threshold   : luminance threshold 0-255 (default 128).
                  Pixels with luminance >= threshold → '1' (active / overlay).
                  Pixels with luminance <  threshold → '0' (transparent).

Output
------
Writes ``rtl/PICTURE_OVERLAY/hdl/MaskRomPkg.vhd`` containing:
  - constants G_MASK_W and G_MASK_H (image dimensions)
  - constant C_MASK_DATA : std_logic_vector packed row-major, MSB = pixel (0,0)

The package is imported by MaskRom.vhd to initialise the inferred BRAM at
synthesis time; no runtime loading is required.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

try:
    import numpy as np
    from PIL import Image as PILImage
except ImportError:
    print("ERROR: Pillow and numpy are required. Run: pip install Pillow numpy")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "rtl" / "PICTURE_OVERLAY" / "hdl" / "MaskRomPkg.vhd"
CHARS_PER_GROUP = 8   # group bits in the constant for readability
GROUPS_PER_LINE = 8   # groups per source line


def _make_mask(image_path: Path, threshold: int) -> tuple[np.ndarray, int, int]:
    """Load image, convert to 1-bit mask array (H x W), return (mask, w, h)."""
    img = PILImage.open(image_path).convert("L")   # grayscale
    arr = np.asarray(img, dtype=np.uint8)
    mask = (arr >= threshold).astype(np.uint8)     # 1 where active
    h, w = mask.shape
    return mask, w, h


def _mask_to_vhdl_bits(mask: np.ndarray) -> str:
    """Flatten mask row-major to a VHDL binary string literal, formatted."""
    flat = mask.flatten().tolist()                  # list of 0/1 ints
    bit_str = "".join(str(b) for b in flat)

    # Split into groups for readability
    groups = textwrap.wrap(bit_str, CHARS_PER_GROUP)
    lines: list[str] = []
    for i in range(0, len(groups), GROUPS_PER_LINE):
        chunk = "_".join(groups[i : i + GROUPS_PER_LINE])
        lines.append(f"        {chunk}")

    return " &\n".join(f'b"{line.strip()}"' for line in lines)


def generate(image_path: Path, threshold: int = 128) -> None:
    mask, w, h = _make_mask(image_path, threshold)
    active_pixels = int(mask.sum())
    total_pixels = w * h
    print(
        f"Mask: {w}x{h}  active={active_pixels}/{total_pixels}"
        f" ({100*active_pixels/total_pixels:.1f}%)  threshold={threshold}"
    )

    bits_vhdl = _mask_to_vhdl_bits(mask)

    vhdl = f"""\
-- AUTO-GENERATED by tools/mask_to_vhdl_rom.py — DO NOT EDIT MANUALLY.
-- Source image : {image_path.name}
-- Dimensions   : {w} x {h} pixels
-- Threshold    : >= {threshold} → active ('1')
-- Active pixels: {active_pixels} / {total_pixels} ({100*active_pixels/total_pixels:.1f} %)
-- Total bits   : {total_pixels}

library ieee;
  use ieee.std_logic_1164.all;

package MaskRomPkg is
  -- Image dimensions (pixels).
  constant G_MASK_W : positive := {w};
  constant G_MASK_H : positive := {h};

  -- Flat row-major 1-bit mask.
  -- Index 0 = pixel (col=0, row=0), index W*H-1 = pixel (col=W-1, row=H-1).
  -- '1' = overlay active (replace video pixel with overlay colour).
  -- '0' = transparent (pass video pixel unchanged).
  constant C_MASK_DATA : std_logic_vector(0 to {total_pixels - 1}) :=
    {bits_vhdl};

end package MaskRomPkg;
"""

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(vhdl, encoding="utf-8")
    print(f"Written → {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    src = Path(sys.argv[1])
    if not src.exists():
        print(f"ERROR: file not found: {src}")
        sys.exit(1)

    thr = int(sys.argv[2]) if len(sys.argv) >= 3 else 128
    if not 0 <= thr <= 255:
        print("ERROR: threshold must be in range 0-255")
        sys.exit(1)

    generate(src, thr)
